### PR TITLE
Debian and Free Desktop metadata

### PR DESCRIPTION
**Pull request by eugeneloza**

### CODE REVIEW

**Comment by eugeneloza** [comment]
Hmmm... there should be 2 commits - I have no idea why the second commit is not displayed in the pull request summary...

**Comment by eugeneloza** [comment]
23ff31e2f90b0fd766e697db98c7af4fa271ce2f

**Comment by eugeneloza** [comment]
Oh, it caught up and now correctly shows 3 commits

**Review by michaliskambi — APPROVED** [review]
It all looks good, thank you! Merging and I'll update https://castle-engine.io/ with this immediately too.

**Pull request merged**
